### PR TITLE
Add new ble profiles: Cycling Power Profile and Cycling Speed and Cadence Profile

### PR DESCRIPTION
**Pull request by Abasz**
Having additional BLE profiles would expand the smart devices (particularly smart and fitness watches) that can connect and read data from ORM. Certain smart devices (e.g. many Garmin watches) are not compatible natively with the FTMS or PM5 BLE profile so in order to be able to record an ORM activity a different BLE profile is needed. Also there are smart devices out there that are not compatible with the ANT FE-C protocol so even having that at a later stage would leave room for additional BLE profiles.

This PR adds two new BLE profiles, namely the Cycling Power Profile that includes the necessary data to calculate speed, stroke rate, distance and power and Cycling Speed and Cadence Profile for those devices that are not compatible with CPP (e.g. older Garmin Forerunner Series). 

Of course as the name suggest theses profiles were developed having a cycling activity in mind. Consequently there are two limitations/workarounds:
1) The speed/distance is reported via the wheel revolution count data field where the count is calculated from the distance in centimeters. Consequently on the client device the wheel circumference should be set to 10mm so the client knows how far one reported wheel revolution took the user
2) Certain smart devices (particularly Garmin Watches) are only allow receiving data via these profiles if a cycling activity is selected (i.e. for instance when rowing activity is selected on the Garmin FR255 the data is not processed)

The implementation is decoupled from the rowing engine. It uses the RowingStatistics for getting data. They work by broadcasting certain data that allows the client to calculate the necessary metrics. These are:
- Total stroke count - `totalNumberOfStrokes`
- Last stroke time (or delta time since last stroke) - `lastStrokeTime` that is essentially the `drivePhaseStartTime`
- Last "wheel revolution" time (or delta time since last rotation) - `totalMovingTime`
- Total wheel revolution - `linearDistance` with a rounded centimeter resolution (i.e. converted to cm from m)
- Current power - `cyclePower`

### CODE REVIEW

**Comment by Abasz** [comment]
Done some simulation on testing the accuracy of the data recorded by a Garmin FR 645 (only capable of handling CSC). It seems that the peripheral update interval matters and the recommended time is 250ms

Update interval 1000ms - watch distance: 5919,2m/ORM distance: 5955,7m (diff 0.6%)
image

Update interval 250ms - watch distance: 5943,95m/ORM distance: 5955,7m (diff 0.2%)
image

Based on the above one can conclude that distance is reported with high accuracy even on an interval (where DF tends to change for the recovery and the high intensity part that generally could cause a drift in distance for an approach like the one used by these profile).

The change in the amount of deviation is an actual result of a delay in recording data by the watch as there is an apparent latency on the data processed (it actually reacts to the high intensity sections a bit late but catches up later on). 

I also attached the raw excel file. The first test was highly inaccurate as there was a connection lost by the watch so the distance drift became significant.: [CSC-testing.xlsx](https://github.com/JaapvanEkris/openrowingmonitor/files/10096466/CSC-testing.xlsx)

Of course more real time test would be necessary especially changing the damper setting on the fly that could be considered as a torture test for such approach (as the client is not aware of drag factor at all).

**Comment by JaapvanEkris** [comment]
Hi @Abasz , did some testing on your improvements. Great news: CSC works on my Garmin Venue, which doesn't officially support BLE.

However, I have an issue with the distance recording: I simulated a 2K row on a Concept2, and according to Garmin, I did a 417,65 km cycle activity. I actually like all the badges I just collected, but a bit unexpected. Somewhere, we need some conversion :).

PS: I had some modifications in the pipeline which needed to be cleared before I could test your improvements, so if you could merge them into your repro, that will save us some issues later on.

PPS: Shouldn't we rename the profiles to "BLE Bike Speed + Cadence" and "BLE Bike Power"?

PPPS: would it be possible to systematically rename `lastStrokeTime` to `driveLastStartTime`? The naming scheme includes the moment when the data is updated (to help understand what is expected to change at any given moment, as many metrics are phase dependent).

**Comment by Abasz** [comment]
> Hi @Abasz , did some testing on your improvements. Great news: CSC works on my Garmin Venue, which doesn't officially support BLE.
> 
> However, I have an issue with the distance recording: I simulated a 2K row on a Concept2, and according to Garmin, I did a 417,65 km cycle activity. I actually like all the badges I just collected, but a bit unexpected. Somewhere, we need some conversion :).

Did you change the wheel circumference to 10mm (i.e. 1cm)? As default it is set to 2 meter something. This is should be done in sensor menu

> 
> PS: I had some modifications in the pipeline which needed to be cleared before I could test your improvements, so if you could merge them into your repro, that will save us some issues later on.
Can you please check if rebasing the pull request branch on the EngingeRedisgin branch is possible as suggested by a early this year update to github: https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

I have never done via this feature and also this option is not visible on my PR page (so I am not sure what is going on). If this is not working I will do it the "legacy" way :)

> 
> PPS: Shouldn't we rename the profiles to "BLE Bike Speed + Cadence" and "BLE Bike Power"?
We can, the only reason I used CSC and CPS is that those are short and easy to select in the settings. Or do you mean the name of the BLE device? if the latter the BLE Bike Speed + Cadence will be too long so it will be trimmed (advertising only supports 31 bytes and that need to include the UUIDs, appearance data etc along with the name). Also I wanted to give the ability to the user to use a unified name. Honestly there should be a general settings for the device name, and then we should append the abbreviation at the end. But such suffix might as well left out as due to the appearance setting the type of the BLE sensor will be apparent to the client (I lean to this latter), apart from FTMS Bike and Rower.

> PPPS: would it be possible to systematically rename lastStrokeTime to driveLastStartTime? The naming scheme includes the moment when the data is updated (to help understand what is expected to change at any given moment, as many metrics are phase dependent).

Yes, sure, I used this name as it is what is expected by BLE profile (last time the stroke count was incremented). My only issue with the name driveLastStartTime is that it requires understanding of the way the rowing engine works, i.e. that the stroke count is always updated at the start of the next drive. I wanted to remove the need for this knowladge

**Comment by JaapvanEkris** [comment]
> > However, I have an issue with the distance recording: I simulated a 2K row on a Concept2, and according to Garmin, I did a 417,65 km cycle activity. I actually like all the badges I just collected, but a bit unexpected. Somewhere, we need some conversion :).
> 
> Did you change the wheel circumference to 10mm (i.e. 1cm)? As default it is set to 2 meter something. This is should be done in sensor menu

Ah! That explains a lot. Is there a reason we use a 1cm wheel circumference? AFAIK, in rowing we typically round to 10 centimeters (i.e. the PM5 and BLE interfaces)? I ask because there are a lot more idiots like me who forget to change this setting and end up cycling quite a bit :).

> > PPS: Shouldn't we rename the profiles to "BLE Bike Speed + Cadence" and "BLE Bike Power"?

> We can, the only reason I used CSC and CPS is that those are short and easy to select in the settings. Or do you mean the name of the BLE device? if the latter the BLE Bike Speed + Cadence will be too long so it will be trimmed (advertising only supports 31 bytes and that need to include the UUIDs, appearance data etc along with the name). Also I wanted to give the ability to the user to use a unified name. Honestly there should be a general settings for the device name, and then we should append the abbreviation at the end. But such suffix might as well left out as due to the appearance setting the type of the BLE sensor will be apparent to the client (I lean to this latter), apart from FTMS Bike and Rower.

Sorry, I was a bit fuzzy on this comment. I aimed for the displaytext in the GUI. On all other places, short is better.

> > PPPS: would it be possible to systematically rename lastStrokeTime to driveLastStartTime? The naming scheme includes the moment when the data is updated (to help understand what is expected to change at any given moment, as many metrics are phase dependent).
> 
> Yes, sure, I used this name as it is what is expected by BLE profile (last time the stroke count was incremented). My only issue with the name driveLastStartTime is that it requires understanding of the way the rowing engine works, i.e. that the stroke count is always updated at the start of the next drive. I wanted to remove the need for this knowladge

Well, we are building a rowing monitor, and the issue is that most metrics are dependent on some sort of state. By making this explicit, especially at the areas far away from the engine, you know what to expect. I needed this for some interfaces (especially the PM5 one), these definitions actually impact the behaviour of the interface, so broadcasting specific metrics in the wrong part of the stroke (i.e. a drivelength at the end of a recovery) can lead to the interface misbehaving as data is inconsistent (this led to early versions of EXR crashing or not starting). For troubleshooting this kind of specifics, it really helps seeing what is supposed to belong to what. I admit that in the FTMS Bike session it makes less sense, but keeping a strong focus on what is what is important: the start time of a stroke is ambigously defined (some start a stroke at the drive, some at the recovery, we can do both). Depending on the interface, on or the other definition prevails (this was an issue with our initial tcx and PM5 set-up).

**Comment by Abasz** [comment]
> Ah! That explains a lot. Is there a reason we use a 1cm wheel circumference? AFAIK, in rowing we typically round to 10 centimeters (i.e. the PM5 and BLE interfaces)? I ask because there are a lot more idiots like me who forget to change this setting and end up cycling quite a bit :).

The reason is simple: this gives the best resolution accuracy. If we were to use 10cm than the resolution of the distance on the client side would be 10cm. Generally with a DF of 108-110 one full rotation is equal to 21 cm. This means that due to the rounding, with lower resolution the instantaneous speed could be rather volatile. With higher resolution (like 1cm) the deviation re rounding is less. So keeping it at 1cm is fine.

> Sorry, I was a bit fuzzy on this comment. I aimed for the displaytext in the GUI. On all other places, short is better.

Sure I will change that, it makes sens 

> Well, we are building a rowing monitor, and the issue is that most metrics are dependent on some sort of state. By making this explicit, especially at the areas far away from the engine, you know what to expect. I needed this for some interfaces (especially the PM5 one), these definitions actually impact the behaviour of the interface, so broadcasting specific metrics in the wrong part of the stroke (i.e. a drivelength at the end of a recovery) can lead to the interface misbehaving as data is inconsistent (this led to early versions of EXR crashing or not starting). For troubleshooting this kind of specifics, it really helps seeing what is supposed to belong to what. I admit that in the FTMS Bike session it makes less sense, but keeping a strong focus on what is what is important: the start time of a stroke is ambigously defined (some start a stroke at the drive, some at the recovery, we can do both). Depending on the interface, on or the other definition prevails (this was an issue with our initial tcx and PM5 set-up).

Sure I will rename it, no problems.

**Comment by JaapvanEkris** [comment]
> > Ah! That explains a lot. Is there a reason we use a 1cm wheel circumference? AFAIK, in rowing we typically round to 10 centimeters (i.e. the PM5 and BLE interfaces)? I ask because there are a lot more idiots like me who forget to change this setting and end up cycling quite a bit :).
> 
> The reason is simple: this gives the best resolution accuracy. If we were to use 10cm than the resolution of the distance on the client side would be 10cm. Generally with a DF of 108-110 one full rotation is equal to 21 cm. This means that due to the rounding, with lower resolution the instantaneous speed could be rather volatile. With higher resolution (like 1cm) the deviation re rounding is less. So keeping it at 1cm is fine.

Thanks, that explains it. I've been playing with it in the new sensor setting, and it works perfectly. I'll await your changes and then start reviewing the code. Great work!

**Comment by Abasz** [comment]
@JaapvanEkris For me the branch shows no conflicts. Or which review note are you referring to?

**Comment by JaapvanEkris** [comment]
> @JaapvanEkris For me the branch shows no conflicts. Or which review note are you referring to?

I added a note whether it would be wise to put the parameters somewhere in a separate file (or reuse the parameters from app/ble/pm5/Pm5Constants.js, which should/could be moved to the common directory??). I think that centralising the various parameters would be a wise step, as @Carlito1979 also is updating the PM5 part and is using similar concepts (like serial number, etc.)(see https://github.com/carlito1979/openrowingmonitor/tree/JaapEngine_CarlAnt). Ideally we would have one central place with valid parameters in a common directory. I'm not sure if they should be part of the config, but having a central list of parameters like you already did with the "common" directory is a great improvement of the code.

**Comment by Abasz** [comment]
Sorry I dont or didnt see that note, but I think I understand it now.

How about this :
- we create a new main folder, "peripherals" that includes ant and ble. Actually the only common within these are the device information (like software version, model etc.). 
- I move peripheralManager.js to this main folder and add a file that includes these shared information
- I can move the BLE result OPcodes to a centralized palce in BLE as those are shared accross ble profile (currently used only be FTMS though
- I can refactor IndoorBikeFeatureCharacteristic and RowerFeatureCharacteristic to use the staticReadChar.js. I noticed that you have a valuereadchar.js already in the pm5 but that has notify as well so that would not be usable for the non-PM5 BLE profiles static reads unfortunately

But most of the strings like UUIDs and things like that relate to the specific ble profile so I would not centralize those but rather leave it as is

Is this what you were looking for?

**Comment by JaapvanEkris** [comment]
> Sorry I dont or didnt see that note, but I think I understand it now.

Yeah, I already thought you missed it. It is a bit hidden type of communication which sometimes is, and sometimes isn't there.

> Is this what you were looking for?

It is the most thorough approach, but perhaps we should wait with such extensive modifications for Carl's solution (and see how these pheripherals all can be positioned well). My proposal is to just move the constants like the serial number, model, name, etc. to one file.

But your argument is a valid one: they are very interface specific and a serial for the PM5 interface might not be useable in the BLE CSC interface. Let's leave it as it is. I'll integrate the pull request tomorrow :)

**Pull request merged**
